feat: divider 디자인 시스템 구현
fun-eat/design-system pull request #13
Opened 2023-07-12 06:03 UTC by hae-on

## Issue

- close #8 

## ✨ 구현한 기능

- divider의 디자인 시스템을 구현하였습니다.

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

2023-07-13 07:10 UTC, xodms0309 requested changes
수고하셨습니다~ 리뷰 확인 해주세용👍

2023-07-13 07:10 UTC, xodms0309 commented on src/Divider/Divider.tsx
> +  type?: 'default' | 'strong' | 'disabled';
`variant`로 수정 부탁드립니다.

2023-07-13 07:10 UTC, xodms0309 commented on src/Divider/Divider.tsx
> +export interface DividerProps extends ComponentPropsWithoutRef<'div'> {
`hr` 태그는 어떠신가요?

2023-07-13 07:10 UTC, xodms0309 commented on src/Divider/Divider.tsx
> +export default Divider;
export 구문이 스타일 위로 가게 수정 부탁드립니다.

2023-07-13 08:00 UTC, Leejin-Yang requested changes
index.ts 파일도 추가해주세요.
그리고 main 추가 설정 있으니 업데이트도 같이 해주세요 👍

2023-07-13 08:08 UTC, hae-on commented
jsDocs 추가 부탁드립니다.

2023-07-14 00:55 UTC, xodms0309 approved these changes
구우우우우웃👍

2023-07-14 04:55 UTC, Leejin-Yang reviewed
찐막 요청

2023-07-14 04:55 UTC, Leejin-Yang commented on src/Divider/Divider.tsx
> +  return <DividerContainer variant={variant} length={length} {...props} />;
```suggestion
  return <hr color={theme.dividerColors[variant]} width={length} size={size} {...props} />;
```

hr 태그의 기본 속성을 사용해도 좋아보여요
https://developer.mozilla.org/ko/docs/Web/HTML/Element/hr

2023-07-14 05:15 UTC, Leejin-Yang approved these changes
수고했어요 👍

2023-07-14 05:19 UTC, merged