feat: Badge 컴포넌트 추가
fun-eat/design-system pull request #14
Opened 2023-07-12 07:01 UTC by xodms0309

## Issue

- close #5

## ✨ 구현한 기능

- Badge 컴포넌트 구현
- Size type 선언 (xs, sm, md, lg, xl)

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

2023-07-13 04:37 UTC, hae-on commented on src/Badge/Badge.stories.tsx
> +      description: 'Badge 컴포넌트에 채워지는 색상',
서술형 부탁드립니다.

2023-07-13 08:02 UTC, Leejin-Yang requested changes
index.ts 파일도 추가해주세요.
그리고 main 추가 설정 있으니 업데이트도 같이 해주세요 👍

2023-07-13 08:08 UTC, hae-on commented
jsDocs 추가 부탁드립니다.

2023-07-13 11:16 UTC, xodms0309 commented
@hae-on @Leejin-Yang 리뷰 반영했습니다 확인해주세요~

2023-07-14 01:38 UTC, hae-on commented on src/Badge/Badge.tsx
> +  color: ${({ textColor }) => textColor};
color와 background의 순서를 바꿔주세요 ❤️

2023-07-14 01:38 UTC, hae-on commented on src/Badge/Badge.tsx
> +  border-radius: 8px;
display
	align-items
	justify-contents
position
	top right bottom left
float
width
height
margin
padding
border
background
font
color
text-decoration
text-align / vertical-align
white-space
other text
content
가상 선택자

2023-07-14 01:42 UTC, xodms0309 commented on src/Badge/Badge.tsx
> +  border-radius: 8px;
ㅋㅋ

2023-07-14 01:45 UTC, xodms0309 commented on src/Badge/Badge.tsx
> +  border-radius: 8px;
[cdef95d](https://github.com/fun-eat/design-system/pull/14/commits/cdef95ddce0a776e9eb2065dd31b730449337ba9)

2023-07-14 01:45 UTC, xodms0309 commented on src/Badge/Badge.tsx
> +  color: ${({ textColor }) => textColor};
수정완 ㅎㅎ [cdef95d](https://github.com/fun-eat/design-system/pull/14/commits/cdef95ddce0a776e9eb2065dd31b730449337ba9)

2023-07-14 04:52 UTC, hae-on approved these changes
수고하셨습니다 👍

2023-07-14 05:19 UTC, merged