feat: Spacing 컴포넌트 추가
fun-eat/design-system pull request #15
Opened 2023-07-12 10:33 UTC by Leejin-Yang

## Issue

- close #9

## ✨ 구현한 기능

- Spacing 컴포넌트 구현

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

2023-07-13 07:56 UTC, xodms0309 requested changes
굿~ 수고하셨어요👍

2023-07-13 07:56 UTC, xodms0309 commented on src/Spacing/Spacing.tsx
> +  height: ${({ direction, size }) => (direction === 'vertical' ? `${size}px` : undefined)};
```suggestion
  width: ${({ direction, size }) => (direction === 'horizontal' ?? `${size}px`)};
  height: ${({ direction, size }) => (direction === 'vertical' ?? `${size}px`)};
```

2023-07-13 07:56 UTC, xodms0309 commented on src/Spacing/Spacing.stories.tsx
> +      description: '여백의 크기 입니다.',
```suggestion
      description: '여백의 방향입니다.',
    },
    size: {
      description: '여백의 크기입니다.',
```

2023-07-13 08:08 UTC, hae-on commented
jsDocs 추가 부탁드립니다.

2023-07-13 16:04 UTC, Leejin-Yang commented
@hae-on @xodms0309
리뷰 감사드려요 😊 아래와 같이 적용했습니다.

- description을 jsDocs로 작성
- 사이즈 스타일 객체로 분리

확인 부탁드려요 👍

2023-07-14 00:58 UTC, xodms0309 approved these changes
LGTM

2023-07-14 05:20 UTC, hae-on approved these changes
수고하셨습니다 👍

2023-07-14 05:22 UTC, merged