feat: BottomSheet 컴포넌트 추가
fun-eat/design-system pull request #16
Opened 2023-07-12 12:17 UTC by xodms0309

## Issue

- close #4 

## ✨ 구현한 기능

- `slideUp` 애니메이션 추가
- BottomSheet 컴포넌트를 `dialog` 태그와 `ref`를 사용하여 구현

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

2023-07-13 07:58 UTC, hae-on commented
바텀시트....어디갔나요....

2023-07-13 08:00 UTC, hae-on requested changes

2023-07-13 08:08 UTC, hae-on commented
jsDocs 추가 부탁드립니다.

2023-07-13 08:52 UTC, Leejin-Yang requested changes
index.ts 파일도 추가해주세요.
그리고 main 추가 설정 있으니 업데이트도 같이 해주세요 👍

2023-07-13 08:52 UTC, Leejin-Yang commented on src/BottomSheet/BottomSheet.tsx
> +import { styled } from 'styled-components';
```suggestion
import styled from 'styled-components';
```

2023-07-13 13:34 UTC, xodms0309 commented
@hae-on @Leejin-Yang 일단 리뷰 반영은 했습니다!
근데 `close` 함수에 대해 jsdoc을 작성하면 스토리북에서 안보이더라고요...? 그래서 일단 description으로 남겨놨습니다. 이거 어떻게 할 지 내일 얘기해봐요

2023-07-14 01:23 UTC, hae-on approved these changes
잘 반영되었네요 수고하셨습니당 👍

2023-07-14 04:51 UTC, hae-on approved these changes
수고하셨습니다 👍

2023-07-14 05:22 UTC, Leejin-Yang approved these changes
수고하셨습니다 👍

2023-07-14 05:23 UTC, merged