feat: Button 컴포넌트 추가
fun-eat/design-system pull request #17
Opened 2023-07-12 14:37 UTC by hae-on

## Issue

- close #2 

## ✨ 구현한 기능

- button 컴포넌트를 구현했습니다.

## 📢 논의하고 싶은 내용

- 사이즈 임의로 figma에 있는 버튼으로 정했습니다. 사이즈에 대한 의견 있으시면 주세요!
- hover 했을 때 스타일을 논의하고 싶습니다. (아직 미구현)

## 🎸 기타

- 특이 사항이 있으면 작성합니다.

2023-07-13 08:09 UTC, hae-on commented
jsDocs 추가 부탁드립니다.

2023-07-13 08:09 UTC, Leejin-Yang requested changes
index.ts 파일도 추가해주세요.
그리고 main 추가 설정 있으니 업데이트도 같이 해주세요 👍

2023-07-13 08:09 UTC, Leejin-Yang commented on src/Button/Button.stories.tsx
> +} satisfies Meta<typeof Button>;
```suggestion
};
```

2023-07-13 08:13 UTC, xodms0309 requested changes
수고하셨습니다~ 리뷰 확인 해주세용 👍

2023-07-13 08:13 UTC, xodms0309 commented on src/Button/Button.stories.tsx
> +      description: 'button의 사이즈입니다.',
Button으로 네이밍 수정 부탁드립니다.

2023-07-13 08:13 UTC, xodms0309 commented on src/Button/Button.stories.tsx
> +} satisfies Meta<typeof Button>;
이 부분은 삭제해도 될 것 같아요

2023-07-13 08:13 UTC, xodms0309 commented on src/Button/Button.tsx
> +  styleType: 'outFilled' | 'filled';
`variant` 로 네이밍 수정해주세요
그리고 `outFilled`를 `outlined`라고 하는 거 어떤가요?

2023-07-13 08:13 UTC, xodms0309 commented on src/Button/Button.tsx
> +  ${({ size }) => buttonTypeStyles[!size ? 'md' : size]};
```suggestion
  ${({ size }) => buttonTypeStyles[size ?? 'md']};
```

2023-07-14 00:58 UTC, xodms0309 approved these changes
LGTM

2023-07-14 05:16 UTC, Leejin-Yang commented on src/Button/Button.tsx
> +
타입 추가

2023-07-14 05:24 UTC, Leejin-Yang approved these changes
수고하셨습니다 👍

2023-07-14 05:25 UTC, merged