feat: Text 컴포넌트 추가
fun-eat/design-system pull request #18
Opened 2023-07-12 17:47 UTC by Leejin-Yang

## Issue

- close #6

## ✨ 구현한 기능

- Text 컴포넌트 구현
- 폰트 관련 theme 추가

## 📢 논의하고 싶은 내용

- Text를 p 또는 span 태그로 사용할 수 있게 하는 중, ComponentPropsWithoutRef에 들어가는 요소를 유동적으로 하기 위해 제네릭을 사용했습니다. 그런데 interface를 사용하니 확장을 할 수 없더라고요.. 그래서 우선 type alias를 사용해 구현해 보았습니다. 타스 고수 도와주세요.!
  - `인터페이스는 개체 형식 또는 정적으로 알려진 멤버가 포함된 개체 형식의 교집합만 확장할 수 있습니다.ts(2312)`
  - [참고 블로그](https://evan-moon.github.io/2020/11/28/making-your-components-extensible-with-typescript/)

아래 두 개는 새 이슈(추가 설정) 제안입니다.
- DefaultTheme의 타입 추론 x. DefaultTheme 타입 확장 제안드립니다.
  - [공식문서: typescript](https://styled-components.com/docs/api#typescript)
- css prop을 받아 커스텀 할 수 있는 여지를 주는건 어떤가요? 반응형 작업이 필요한 경우 유동적으로 할 수 있어 좋아보입니다.
  - [공식문서: css-prop](https://styled-components.com/docs/api#css-prop)
  - [공식문서: babel-plugin](https://styled-components.com/docs/tooling#babel-plugin)

## 🎸 기타

x

2023-07-13 08:08 UTC, xodms0309 requested changes
수고하셨습니다~ 리뷰 확인해주세용 👍

2023-07-13 08:08 UTC, xodms0309 commented on src/Text/Text.tsx
> +  type?: TextTypes;
이것도 `variant`로 네이밍 해야할까요?

2023-07-13 08:08 UTC, xodms0309 commented on src/Text/Text.stories.tsx
> +};
이 
```javascript 
args: {
    children: text,
  },
```
를 meta에 추가하고
아래 Story 코드에서
```javascript
render: ( {children})=> (
<Text>{children}</Text>
)
이런식으로 쓸 수 있지 않을까요?
```

2023-07-13 15:32 UTC, Leejin-Yang commented
@hae-on @xodms0309
리뷰 감사드려요 😊 아래와 같이 적용했습니다.

- 스토리북 meta에 args 추가
- description을 jsDocs로 작성
- props의 type 속성을 element로 수정

추가로 아래 작업 진행했습니다.

- css prop 추가
- 재정의 가능한 컴포넌트 props 타입 추상화

2023-07-14 00:59 UTC, xodms0309 approved these changes
LGTM

2023-07-14 04:50 UTC, hae-on approved these changes
수고하셨습니다 👍

2023-07-14 05:25 UTC, merged